"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
exports.default = RootLayout;
const google_1 = require("next/font/google");
require("./globals.css");
const inter = (0, google_1.Inter)({ subsets: ["latin"], variable: '--font-inter' });
const ibmPlexSerif = (0, google_1.IBM_Plex_Serif)({ subsets: ["latin"], weight: ['400', '700'], variable: '--font-ibm-plex-serif' });
exports.metadata = {
    title: "Future",
    description: "Generated by create next app",
    icons: {
        icon: './icons/logo.svg'
    }
};
function RootLayout({ children, }) {
    return (<html lang="en">
      <body className={`${inter.variable} ${ibmPlexSerif.variable}`}>{children}</body>
    </html>);
}
